---

networks:
  proxy:
    attachable: true
    driver: overlay
    external: true
#volumes:
  #python-libs:

services:
  vscode:
    user: code:src
    image: i8degrees/vscode-server:latest
    build:
      context: .
      dockerfile: "Dockerfile"
    #command: code server
    restart: unless-stopped
    container_name: vscode-server-1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      ".env"
      #".env.dist"
    networks:
      - proxy
    #ports:
    #- "22:22/tcp"

